#!/bin/bash
# Setup script for WrinkleFree-Deployer
#
# This script:
# 1. Loads credentials from .env file
# 2. Configures SkyPilot SSH Node Pools
# 3. Verifies all cloud connections
#
# Usage:
#   source scripts/setup-env.sh
#
# Note: Use 'source' (not 'bash') so environment variables persist in your shell

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "=== WrinkleFree-Deployer Setup ==="
echo ""

# ============================================================================
# Load .env file
# ============================================================================

ENV_FILE="$PROJECT_DIR/.env"

if [ ! -f "$ENV_FILE" ]; then
    echo "ERROR: .env file not found!"
    echo ""
    echo "Please create it from the example:"
    echo "  cp .env.example .env"
    echo "  vim .env  # Add your credentials"
    echo ""
    return 1 2>/dev/null || exit 1
fi

echo "Loading environment from .env..."

# Export all variables from .env
set -a
source "$ENV_FILE"
set +a

echo "  ✓ Environment loaded"
echo ""

# ============================================================================
# Validate required variables
# ============================================================================

echo "Checking required credentials..."

MISSING=""

# Check for at least one cloud provider
if [ -z "$AWS_ACCESS_KEY_ID" ] && [ -z "$GOOGLE_APPLICATION_CREDENTIALS" ] && [ -z "$HETZNER_SERVER_IPS" ]; then
    echo "  ✗ No cloud credentials found"
    MISSING="true"
fi

if [ -n "$AWS_ACCESS_KEY_ID" ]; then
    if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
        echo "  ✗ AWS_SECRET_ACCESS_KEY is missing"
        MISSING="true"
    else
        echo "  ✓ AWS credentials found"
    fi
fi

if [ -n "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
    if [ ! -f "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
        echo "  ✗ GCP service account file not found: $GOOGLE_APPLICATION_CREDENTIALS"
        MISSING="true"
    else
        echo "  ✓ GCP credentials found"
    fi
fi

if [ -n "$HETZNER_SERVER_IPS" ]; then
    echo "  ✓ Hetzner server IPs configured"
fi

if [ -n "$OVHCLOUD_KUBECONFIG_PATH" ]; then
    OVHCLOUD_KUBECONFIG="${OVHCLOUD_KUBECONFIG_PATH/#\~/$HOME}"
    if [ -f "$OVHCLOUD_KUBECONFIG" ]; then
        echo "  ✓ OVHCloud kubeconfig found"
    else
        echo "  ⚠ OVHCloud kubeconfig not found: $OVHCLOUD_KUBECONFIG"
        echo "    Download from: OVHcloud Control Panel → Managed Kubernetes → kubeconfig"
    fi
fi

if [ -n "$MISSING" ]; then
    echo ""
    echo "Please add the missing credentials to .env"
    return 1 2>/dev/null || exit 1
fi

echo ""

# ============================================================================
# Configure SSH Node Pool (if Hetzner IPs provided)
# ============================================================================

if [ -n "$HETZNER_SERVER_IPS" ]; then
    echo "Configuring SkyPilot SSH Node Pool for Hetzner..."

    SSH_KEY_PATH="${HETZNER_SSH_KEY_PATH:-~/.ssh/hetzner_ed25519}"
    SSH_KEY_PATH="${SSH_KEY_PATH/#\~/$HOME}"  # Expand tilde

    # Check SSH key exists
    if [ ! -f "$SSH_KEY_PATH" ]; then
        echo "  ✗ SSH key not found: $SSH_KEY_PATH"
        echo ""
        echo "  Generate one with:"
        echo "    ssh-keygen -t ed25519 -f $SSH_KEY_PATH"
        echo ""
        echo "  Then copy to your servers:"
        echo "    ssh-copy-id -i $SSH_KEY_PATH root@<SERVER_IP>"
        return 1 2>/dev/null || exit 1
    fi

    # Create SSH Node Pool config
    mkdir -p ~/.sky

    # Convert comma-separated IPs to YAML list
    cat > ~/.sky/ssh_node_pools.yaml << EOF
# Auto-generated by setup-env.sh
# Source: WrinkleFree-Deployer/.env

hetzner-base:
  user: root
  identity_file: $SSH_KEY_PATH
  hosts:
EOF

    # Add each IP
    IFS=',' read -ra IPS <<< "$HETZNER_SERVER_IPS"
    for ip in "${IPS[@]}"; do
        ip=$(echo "$ip" | xargs)  # Trim whitespace
        echo "    - $ip" >> ~/.sky/ssh_node_pools.yaml
    done

    echo "  ✓ SSH Node Pool config written to ~/.sky/ssh_node_pools.yaml"
    echo "  ✓ Servers: ${#IPS[@]}"
    echo ""
fi

# ============================================================================
# Configure OVHCloud Kubernetes (if kubeconfig provided)
# ============================================================================

if [ -n "$OVHCLOUD_KUBECONFIG_PATH" ]; then
    OVHCLOUD_KUBECONFIG="${OVHCLOUD_KUBECONFIG_PATH/#\~/$HOME}"

    if [ -f "$OVHCLOUD_KUBECONFIG" ]; then
        echo "Configuring OVHCloud Kubernetes for SkyPilot..."

        # Merge with existing kubeconfig
        mkdir -p ~/.kube
        if [ -f ~/.kube/config ]; then
            echo "  Merging OVHCloud kubeconfig with existing config..."
            # Backup existing config
            cp ~/.kube/config ~/.kube/config.backup.$(date +%s)
            # Merge configs
            KUBECONFIG=~/.kube/config:$OVHCLOUD_KUBECONFIG kubectl config view --flatten > ~/.kube/config.merged
            mv ~/.kube/config.merged ~/.kube/config
            chmod 600 ~/.kube/config
        else
            cp "$OVHCLOUD_KUBECONFIG" ~/.kube/config
            chmod 600 ~/.kube/config
        fi

        echo "  ✓ OVHCloud kubeconfig merged"

        # Configure SkyPilot to use the OVHCloud context
        if [ -n "$OVHCLOUD_K8S_CONTEXT" ]; then
            mkdir -p ~/.sky
            # Add to SkyPilot config if not already there
            if [ -f ~/.sky/config.yaml ]; then
                if ! grep -q "allowed_contexts:" ~/.sky/config.yaml; then
                    echo "" >> ~/.sky/config.yaml
                    echo "kubernetes:" >> ~/.sky/config.yaml
                    echo "  allowed_contexts:" >> ~/.sky/config.yaml
                    echo "    - $OVHCLOUD_K8S_CONTEXT" >> ~/.sky/config.yaml
                fi
            else
                cat > ~/.sky/config.yaml << EOF
kubernetes:
  allowed_contexts:
    - $OVHCLOUD_K8S_CONTEXT
  networking: portforward
EOF
            fi
            echo "  ✓ SkyPilot configured for OVHCloud context: $OVHCLOUD_K8S_CONTEXT"
        fi

        echo ""
    fi
fi

# ============================================================================
# Verify SkyPilot setup
# ============================================================================

echo "Verifying SkyPilot configuration..."

if ! command -v sky &> /dev/null; then
    echo "  ✗ SkyPilot not installed"
    echo ""
    echo "  Install with:"
    echo "    uv sync"
    return 1 2>/dev/null || exit 1
fi

echo ""
echo "Running 'sky check'..."
echo "----------------------------------------"
sky check
echo "----------------------------------------"
echo ""

# ============================================================================
# Initialize SSH Node Pool (if configured)
# ============================================================================

if [ -n "$HETZNER_SERVER_IPS" ]; then
    echo "Do you want to initialize the SSH Node Pool now?"
    echo "This will install SkyPilot runtime on your Hetzner servers."
    echo ""
    read -p "Initialize? (y/N): " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo "Initializing SSH Node Pool..."
        sky ssh up
        echo ""
        echo "Verifying SSH Node Pool..."
        sky check ssh
    else
        echo "Skipped. Run 'sky ssh up' later to initialize."
    fi
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Deploy your service:"
echo "     sky serve up skypilot/service.yaml --name $SERVICE_NAME"
echo ""
echo "  2. Check status:"
echo "     sky serve status $SERVICE_NAME"
echo ""
echo "  3. Get endpoint:"
echo "     sky serve status $SERVICE_NAME"
echo ""
