# WrinkleFree Training Job
#
# Single YAML for all training configs. Set TRAINING_CONFIG env var to select:
#   - base: Combined CE + DLM (recommended)
#   - bitdistill_full: Knowledge distillation
#   - lrc_run: Low-Rank Correction
#   - salient_run: AWQ-style salient columns
#   - sft_run: Supervised fine-tuning
#   - smoke_test: Quick validation (30 steps)
#
# Usage:
#   cd packages/deployer
#   source credentials/.env
#
#   # Default (base config)
#   sky launch skypilot/train.yaml -y --cluster wf-train
#
#   # Specific config
#   sky launch skypilot/train.yaml -y --cluster wf-train \
#     --env TRAINING_CONFIG=lrc_run --env MODEL=qwen3_0.6b
#
#   # With total tokens
#   sky launch skypilot/train.yaml -y --cluster wf-train \
#     --env TRAINING_CONFIG=base --env TOTAL_TOKENS=10B
#
# Or use the CLI:
#   wf train -m qwen3_4b -t base --cloud nebius
#
# Monitor:
#   sky logs wf-train
#
# Down:
#   sky down wf-train -y

name: wrinklefree-train

resources:
  accelerators: H100:1
  memory: 64+
  disk_size: 200
  use_spot: false
  cloud: nebius

# Run from monorepo root
workdir: .

file_mounts:
  /tmp/gcp-creds.json: packages/deployer/credentials/gcp-service-account.json
  /tmp/credentials.env: packages/deployer/credentials/.env
  /tmp/global.env: ~/.config/.env.global

envs:
  GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-creds.json
  GOOGLE_CLOUD_PROJECT: wrinklefree-481904
  GCS_BUCKET: wrinklefree-checkpoints
  # Configurable via --env or core.py
  MODEL: smollm2_135m
  TRAINING_CONFIG: base
  TOTAL_TOKENS: ""  # e.g., "10B" or "1B"
  HYDRA_OVERRIDES: ""  # Additional Hydra overrides (space-separated)
  # Fixed
  WANDB_PROJECT: wrinklefree_v2
  HF_HUB_ENABLE_HF_TRANSFER: "1"
  PYTHONUNBUFFERED: "1"

setup: |
  set -e
  cd ~/sky_workdir

  # Install uv
  if ! command -v uv &> /dev/null; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.cargo/bin:$PATH"
  fi

  # Install gcloud for GCS uploads
  if ! command -v gcloud &> /dev/null; then
    printf "Installing gcloud CLI...\n"
    curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts --install-dir=$HOME
    export PATH="$HOME/google-cloud-sdk/bin:$PATH"
  fi

  # Authenticate gcloud
  gcloud auth login --cred-file=/tmp/gcp-creds.json --quiet || true
  gcloud config set project wrinklefree-481904

  uv sync --all-packages
  echo "Setup complete!"

run: |
  set -e
  cd ~/sky_workdir
  export PATH="$HOME/.cargo/bin:$HOME/google-cloud-sdk/bin:$PATH"

  source /tmp/credentials.env
  source /tmp/global.env 2>/dev/null || true
  export HF_TOKEN="${HUGGINGFACE_WRITE_TOKEN}"

  CHECKPOINT_DIR="/tmp/checkpoints"
  mkdir -p $CHECKPOINT_DIR

  # Build dispatch args
  DISPATCH_ARGS="--training-config $TRAINING_CONFIG --model $MODEL"
  DISPATCH_ARGS="$DISPATCH_ARGS --checkpoint-dir $CHECKPOINT_DIR"
  DISPATCH_ARGS="$DISPATCH_ARGS --gcs-bucket $GCS_BUCKET"
  DISPATCH_ARGS="$DISPATCH_ARGS --wandb-project $WANDB_PROJECT"

  if [ -n "$TOTAL_TOKENS" ]; then
    DISPATCH_ARGS="$DISPATCH_ARGS --total-tokens $TOTAL_TOKENS"
  fi

  # Run dispatch script (pass HYDRA_OVERRIDES as extra args)
  # stdbuf ensures line-buffered output for real-time logs
  stdbuf -oL -eL uv run --package wf-train python -u packages/deployer/scripts/dispatch_train.py $DISPATCH_ARGS $HYDRA_OVERRIDES

  echo ""
  echo "================================================"
  echo "Training Complete!"
  echo "================================================"

  # Verify checkpoints
  echo ""
  echo "[Verify] Checkpoints:"
  find $CHECKPOINT_DIR -type f -name "*.ckpt" 2>/dev/null | head -10 || echo "No checkpoints found"
